<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-08T10:12:15Z" name="Suite" finished-at="2022-07-08T10:13:05Z" duration-ms="49692">
    <groups>
    </groups>
    <test started-at="2022-07-08T10:12:15Z" name="Login" finished-at="2022-07-08T10:13:05Z" duration-ms="49692">
      <class name="amazon.Login">
        <test-method is-config="true" signature="Initialize()[pri:0, instance:amazon.Login@607b2792]" started-at="2022-07-08T15:42:15Z" name="Initialize" finished-at="2022-07-08T15:42:22Z" duration-ms="6629" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initialize -->
        <test-method signature="titleVerification()[pri:0, instance:amazon.Login@607b2792]" started-at="2022-07-08T15:42:22Z" name="titleVerification" description="To Verify the HomePage Title" finished-at="2022-07-08T15:42:26Z" duration-ms="4339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleVerification -->
        <test-method signature="signinWithNoData()[pri:0, instance:amazon.Login@607b2792]" started-at="2022-07-08T15:42:26Z" name="signinWithNoData" description="To Verify the Error Message When No Data is Entered" finished-at="2022-07-08T15:42:34Z" duration-ms="8061" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signinWithNoData -->
        <test-method signature="signinWithInvalidData()[pri:0, instance:amazon.Login@607b2792]" started-at="2022-07-08T15:42:34Z" name="signinWithInvalidData" description="To Verify the Error Message When Email Id is Invalid" finished-at="2022-07-08T15:42:47Z" duration-ms="12398" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signinWithInvalidData -->
        <test-method signature="signinWithInvalidPassword()[pri:0, instance:amazon.Login@607b2792]" started-at="2022-07-08T15:42:47Z" name="signinWithInvalidPassword" description="To Verify the Error Message When Password is Invalid" finished-at="2022-07-08T15:42:55Z" duration-ms="8870" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your password is incorrect] but found [To better protect your account, please re-enter your password and then enter the characters as they are shown in the image below.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your password is incorrect] but found [To better protect your account, please re-enter your password and then enter the characters as they are shown in the image below.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at amazon.Login.signinWithInvalidPassword(Login.java:88)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signinWithInvalidPassword -->
        <test-method signature="signinWithValidData()[pri:0, instance:amazon.Login@607b2792]" started-at="2022-07-08T15:42:56Z" name="signinWithValidData" description="To Verify if able to login with valid credentials" finished-at="2022-07-08T15:43:05Z" duration-ms="8927" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signinWithValidData -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:amazon.Login@607b2792]" started-at="2022-07-08T15:43:05Z" name="TearDown" finished-at="2022-07-08T15:43:05Z" duration-ms="308" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- amazon.Login -->
    </test> <!-- Login -->
  </suite> <!-- Suite -->
</testng-results>
